"""refactor_part_defects_to_json

Revision ID: 072579ba44cd
Revises: 837eb48e2c08
Create Date: 2026-06-24 18:27:00.544817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072579ba44cd'
down_revision: Union[str, Sequence[str], None] = '837eb48e2c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part_defects', sa.Column('defects_data', sa.JSON(), nullable=False))
    op.add_column('part_defects', sa.Column('cam_id', sa.String(length=50), nullable=True))
    op.add_column('part_defects', sa.Column('trigger_id', sa.String(length=50), nullable=True))
    op.add_column('part_defects', sa.Column('part_ok', sa.Boolean(), nullable=False))
    op.add_column('part_defects', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('part_defects', 'thread_missing')
    op.drop_column('part_defects', 'rust')
    op.drop_column('part_defects', 'dent')
    op.drop_column('part_defects', 'scratch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part_defects', sa.Column('scratch', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('part_defects', sa.Column('dent', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('part_defects', sa.Column('rust', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('part_defects', sa.Column('thread_missing', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('part_defects', 'created_at')
    op.drop_column('part_defects', 'part_ok')
    op.drop_column('part_defects', 'trigger_id')
    op.drop_column('part_defects', 'cam_id')
    op.drop_column('part_defects', 'defects_data')
    # ### end Alembic commands ###
