"""initial tablesfor SCM

Revision ID: 38715d97e1e4
Revises: 
Create Date: 2026-06-18 15:57:17.362668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38715d97e1e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('parts',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('part_code', sa.String(length=50), nullable=False),
    sa.Column('part_name', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('parts_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('part_weight', sa.Float(), nullable=True),
    sa.Column('part_height', sa.Float(), nullable=True),
    sa.Column('part_width', sa.Float(), nullable=True),
    sa.Column('part_diameter', sa.Float(), nullable=True),
    sa.Column('plc_speed_factor_feeder1', sa.Float(), server_default='1.0', nullable=True),
    sa.Column('plc_speed_factor_feeder2', sa.Float(), server_default='1.0', nullable=True),
    sa.Column('plc_speed_factor_hopper', sa.Float(), server_default='1.0', nullable=True),
    sa.Column('plc_gate_hopper_opening_factor', sa.Float(), server_default='1.0', nullable=True),
    sa.Column('plain_primary', sa.Float(), server_default='1.0', nullable=True),
    sa.Column('plain_secondary', sa.Float(), server_default='1.0', nullable=True),
    sa.Column('corrugated_primary', sa.Float(), server_default='1.0', nullable=True),
    sa.Column('corrugated_secondary', sa.Float(), server_default='1.0', nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('part_id'),
    sa.UniqueConstraint('part_code')
    )
    op.create_index(op.f('ix_parts_part_id'), 'parts', ['part_id'], unique=False)
    op.create_table('company_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('part_code', sa.String(length=50), nullable=False),
    sa.Column('part_name', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('batching_mode', sa.Text(), server_default='auto', nullable=False),
    sa.Column('no_of_batches', sa.Integer(), nullable=True),
    sa.Column('batch_delay', sa.Integer(), nullable=True),
    sa.Column('number_of_parts_per_batches', sa.Integer(), nullable=True),
    sa.Column('part_count', sa.Integer(), nullable=False),
    sa.Column('batch_counts', sa.JSON(), nullable=True),
    sa.Column('parts_per_minute', sa.Integer(), nullable=True),
    sa.Column('session_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('session_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('session_weight', sa.Float(), nullable=True),
    sa.Column('order_no', sa.String(length=50), nullable=True),
    sa.Column('is_calibration', sa.Boolean(), nullable=True),
    sa.Column('calibration_expected_per_run', sa.Integer(), nullable=True),
    sa.Column('calibration_total_runs', sa.Integer(), nullable=True),
    sa.Column('calibration_runs', sa.JSON(), nullable=True),
    sa.Column('calibration_avg_count', sa.Float(), nullable=True),
    sa.Column('calibration_avg_accuracy', sa.Float(), nullable=True),
    sa.Column('calibration_passed', sa.Boolean(), nullable=True),
    sa.Column('calibration_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_sessions_id'), 'company_sessions', ['id'], unique=False)
    op.create_table('part_measurement_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('actual_measurement_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_operation_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('mode_of_operation', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("mode_of_operation IN ('Counting', 'Defect Detection', 'Measurement', 'Measurement & Defect Detection')", name='operation_mode_check'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('thread_missing', sa.Integer(), nullable=True),
    sa.Column('dent', sa.Integer(), nullable=True),
    sa.Column('scratch', sa.Integer(), nullable=True),
    sa.Column('rust', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['company_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('measured_realtime_data', sa.JSON(), nullable=True),
    sa.Column('overall_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['company_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_measurements')
    op.drop_table('part_defects')
    op.drop_table('part_operation_modes')
    op.drop_table('part_measurement_configs')
    op.drop_index(op.f('ix_company_sessions_id'), table_name='company_sessions')
    op.drop_table('company_sessions')
    op.drop_index(op.f('ix_parts_part_id'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
