"""add counting_type to company_sessions

Revision ID: 837eb48e2c08
Revises: 38715d97e1e4
Create Date: 2026-06-24 10:10:14.445101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837eb48e2c08'
down_revision: Union[str, Sequence[str], None] = '38715d97e1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_sessions', sa.Column('counting_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_sessions', 'counting_type')
    # ### end Alembic commands ###
