"""baseline: freeze OSM schema v1

Revision ID: fdad727971a1
Revises: 
Create Date: 2026-08-30 16:26:51.408603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdad727971a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('operator','administrator','superadministrator')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('parts',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('part_code', sa.String(length=50), nullable=False),
    sa.Column('part_name', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('part_weight', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('defects', sa.JSON(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('has_defect_pipeline', sa.Boolean(), nullable=False),
    sa.Column('has_measurement_pipeline', sa.Boolean(), nullable=False),
    sa.Column('active_config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['active_config_id'], ['part_configs.id'], name='fk_parts_active_config', use_alter=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('part_id'),
    sa.UniqueConstraint('part_code')
    )
    op.create_index(op.f('ix_parts_part_id'), 'parts', ['part_id'], unique=False)
    op.create_table('part_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_yaml', sa.Text(), nullable=False),
    sa.Column('config_path', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_configs_id'), 'part_configs', ['id'], unique=False)
    op.create_table('part_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('part_config_id', sa.Integer(), nullable=False),
    sa.Column('part_code', sa.String(length=50), nullable=False),
    sa.Column('part_name', sa.Text(), nullable=False),
    sa.Column('trigger_id', sa.String(length=50), nullable=False),
    sa.Column('trigger_type', sa.Text(), nullable=False),
    sa.Column('trigger_source', sa.Text(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_fired', sa.Integer(), nullable=False),
    sa.Column('total_passed', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('session_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('session_end', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("trigger_source IN ('simulation','plc','ui_button')", name='ck_session_trigger_source'),
    sa.CheckConstraint("trigger_type IN ('inspection','counting')", name='ck_session_trigger_type'),
    sa.ForeignKeyConstraint(['part_config_id'], ['part_configs.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_sessions_id'), 'part_sessions', ['id'], unique=False)
    op.create_table('session_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.String(length=50), nullable=False),
    sa.Column('ring_part_id', sa.Integer(), nullable=False),
    sa.Column('trigger_fire_no', sa.Integer(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('overall_passed', sa.Boolean(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('plc_written', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['part_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_results_id'), 'session_results', ['id'], unique=False)
    op.create_index(op.f('ix_session_results_ring_part_id'), 'session_results', ['ring_part_id'], unique=False)
    op.create_index('ix_session_results_session_ring_part', 'session_results', ['session_id', 'ring_part_id'], unique=False)
    op.create_table('camera_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_result_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('pipeline_name', sa.String(length=50), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('detection_bbox', sa.JSON(), nullable=True),
    sa.Column('is_defective', sa.Boolean(), nullable=True),
    sa.Column('defect_label', sa.Text(), nullable=True),
    sa.Column('defect_confidence', sa.Float(), nullable=True),
    sa.Column('all_detections', sa.JSON(), nullable=True),
    sa.Column('measurement_data', sa.JSON(), nullable=True),
    sa.Column('measurement_passed', sa.Boolean(), nullable=True),
    sa.Column('camera_passed', sa.Boolean(), nullable=True),
    sa.Column('annotated_image', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['session_result_id'], ['session_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_results_id'), 'camera_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_camera_results_id'), table_name='camera_results')
    op.drop_table('camera_results')
    op.drop_index('ix_session_results_session_ring_part', table_name='session_results')
    op.drop_index(op.f('ix_session_results_ring_part_id'), table_name='session_results')
    op.drop_index(op.f('ix_session_results_id'), table_name='session_results')
    op.drop_table('session_results')
    op.drop_index(op.f('ix_part_sessions_id'), table_name='part_sessions')
    op.drop_table('part_sessions')
    op.drop_index(op.f('ix_part_configs_id'), table_name='part_configs')
    op.drop_table('part_configs')
    op.drop_index(op.f('ix_parts_part_id'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
